//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSite
    {
        public int customerSiteId { get; set; }
        public int customerId { get; set; }
        public string alphabeticId { get; set; }
        public string siteName { get; set; }
        public Nullable<System.DateTime> dateOfLastSale { get; set; }
        public int salesAmount { get; set; }
        public int wayOfDeliveryId { get; set; }
        public Nullable<bool> markOfDeletion { get; set; }
        public int paymentDisruptionId { get; set; }
        public Nullable<int> sales { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual PaymentDisruption PaymentDisruption { get; set; }
        public virtual WayOfDelivery WayOfDelivery { get; set; }
    }
}
