//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.CustomerSite = new HashSet<CustomerSite>();
        }
    
        public int customerId { get; set; }
        public int userId { get; set; }
        public string alphabeticId { get; set; }
        public int customerGroupId { get; set; }
        public string customerName { get; set; }
        public string StreetAddress { get; set; }
        public string ZipCode { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public Nullable<bool> ispostaladdsame { get; set; }
        public string postalStreetAddress { get; set; }
        public string postalZipCode { get; set; }
        public string postalcity { get; set; }
        public string contactpersonName { get; set; }
        public string emailAddress { get; set; }
        public string title { get; set; }
        public string phoneNumber { get; set; }
        public int creditLimit { get; set; }
        public decimal discountRate { get; set; }
        public bool createcustomersite { get; set; }
    
        public virtual CustomerGroup CustomerGroup { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<CustomerSite> CustomerSite { get; set; }
    }
}
