//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDisruption
    {
        public PaymentDisruption()
        {
            this.CustomerSite = new HashSet<CustomerSite>();
        }
    
        public int paymentDisruptionId { get; set; }
        public string paymentDisruptionType { get; set; }
    
        public virtual ICollection<CustomerSite> CustomerSite { get; set; }
    }
}
