//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Admin = new HashSet<Admin>();
            this.Employee = new HashSet<Employee>();
        }
    
        public int userId { get; set; }
        public int roleId { get; set; }
        public string userName { get; set; }
        public string passWord { get; set; }
    
        public virtual ICollection<Admin> Admin { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Employee> Employee { get; set; }
        public virtual Role Role { get; set; }
    }
}
